<style>
div#left_header{
	float:left;
	margin-left:50px;
	width:101px;
	height:60px;
}

div#left_header a{
	width:100%;
	height:100%;
	display:block;
}

div.info{
    color: #042A71;
    font-size: 30px;
    padding: 10px;
    text-indent: 30px;
}
</style>
<div id="left_header">
	<a href="/"><img src="/images/Logo.png" /></a>
</div>
<div class="info">由我影视导航,为您轻松找到想看的影片而努力!</div>