<style>
#about{
	margin:20px auto;
	padding:30px;
	line-height:2em;
	width:800px;
}
#about h1{
	text-align:center;
}
#about h2{
	margin:10px 0;
}
</style>
<div id="about">
	<h1>关于inu5.com</h1>
	<h2>关于网站</h2>
	<h3>inu5.com的目标：给您尽可能多的影视链接资源。</h3>
	<p>inu5.com于2012年4月25日上线。<p>
	<p>inu5.com整理网络中存在的各个影视资源的链接，包括下载资源和在线资源。您使用的相关资源并不属于inu5.com，相关的服务协议和inu5.com无关。<p>
	<h3>为什么要使用inu5.com</h3>
	<p>1、inu5.com的搜索功能，不仅仅会搜索inu5.com站内的信息，当您搜索的影片在站内无法找到的时候，inu5.com会通过内部的一个库去网络中搜索您需要的影片。</p>
	<p>2、如果您在inu5.com没有找到您需要的信息，inu5.com会不定期去网络中查找你搜索的信息。所以可能出现一种情况：你在搜索的时候没有找到你要的信息，但是可能1个小时、或者1~3天以后你就能找到你要的信息</p>
	<h2>关于我</h2>
	<p>QQ：787211820</p>
	<p>E-mail：jcy95888387@yahoo.com.cn</p>
	<p>网易博客：<a href="http://inu5.blog.163.com" target="_blank">http://inu5.blog.163.com</a></p>
</div>