<style>
#sitemap{
	margin-top:20px;
	background:#F6FFDD;
	border:1px solid #97BF2B;
	padding:30px;
}
#sitemap h1{
	text-align:center;
}
#sitemap table{
	width:100%;
	border:1px solid;
	border-collapse: collapse;
	margin:10px 0;
}
#sitemap table tr td{
	text-align:center;
	padding:20px 5px;
}
</style>
<div id="sitemap">
	<h1>inu5.com网站地图</h1>
	<table>
		<tr>
			<td colspan="15" style="border-bottom:1px solid;"><a href="/">首页</a></td>
		</tr>
		<tr>
			<td colspan="7" style="border-right:1px solid;"><a href="/television/movie/list/?category=01">电影</a></td>
			<td colspan="5" style="border-right:1px solid;"><a href="/television/movie/list/?category=02">电视</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=03">综艺</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=04">动漫</a></td>
			<td><a href="/television/movie/list/?category=05">纪录片</a></td>
		</tr>
		<tr>
			<td><a href="/television/movie/list/?category=01001">动作片</a></td>
			<td><a href="/television/movie/list/?category=01002">喜剧片</a></td>
			<td><a href="/television/movie/list/?category=01003">科幻片</a></td>
			<td><a href="/television/movie/list/?category=01004">爱情片</a></td>
			<td><a href="/television/movie/list/?category=01005">恐怖片</a></td>
			<td><a href="/television/movie/list/?category=01006">战争片</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=01007">剧情片</a></td>
			<td><a href="/television/movie/list/?category=02001">港台剧</a></td>
			<td><a href="/television/movie/list/?category=02002">大陆剧</a></td>
			<td><a href="/television/movie/list/?category=02003">日韩剧</a></td>
			<td><a href="/television/movie/list/?category=02004">欧美剧</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=02005">海外剧</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=03001">综艺</a></td>
			<td style="border-right:1px solid;"><a href="/television/movie/list/?category=04001">动漫</a></td>
			<td><a href="/television/movie/list/?category=05001">纪录片</a></td>
		</tr>
	</table>
</div>