<!DOCTYPE html>
<html>
<head>
	<meta name="baidu-site-verification" content="C9QKZT69wSVKSrnH" />
	<meta name="chinaz-site-verification" content="8b77bc1c-97ea-44d5-bc83-e3a2c68fa312" />
	<meta name="google-site-verification" content="CCbVahem7Ve83OKF1aWYXSYAXzBCvQ1ifNX55tiUlJ0" />
	<meta name="robots" content="index,follow">
	<meta name="googlebot" content="index,follow">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{{title}}</title>
	<meta name="keywords" content="{{keywords}}" />
	<meta name="description" content="{{description;}}" />
	<link rel="shortcut icon" href="/favicon.ico" />
	<link href="/css/television/default.css" rel="stylesheet" type="text/css" />
	<script src="/js/jquery/jquery.js"></script>
	<script src="/js/television/default.js"></script>
</head>
<body>
	<p style="color:red;"><strong>公告</strong>：1、本站正在进行重要改版，敬请期待.......<br/>2、请使用搜索框查找您要看的影片，如果没有搜索结果，inu5.com会留下您的搜索记录，为你找片。</p>
	<div class="header">
		{{include(header)}}
	</div>
	<div class="navgater">
		{{include(navgater)}}
	</div>
	<div class="searchBar">
		{{include(searchBar)}}
	</div>
	<div class="content">
		<div class="center">
		{{content}}
		</div>
		<div style="clear:both;"></div>
	</div>
	<div class="footer">
		{{include(footer)}}
	</div>
</body>
</html>
