<link href="/css/intranet/television/website/dialog.css" rel="stylesheet" type="text/css" />
<form onsubmit="return false">
<input type="hidden" name="website_id" value="0" />
	<table>
		<tr>
			<th><label for="website_name">网站名称：</label></th>
			<td><input id="website_name" type="text" name="website_name" class="width95b validation"/></td>
		</tr>
		<tr>
			<th><label for="website_check_flag">通过验证：</label></th>
			<td>
				<input type="radio" name="website_check_flag" checked="checked" value="F" />否
				<input type="radio" name="website_check_flag" value="T" />是
			</td>
		</tr>
		<tr>
			<th><label for="website_url">网站URL：</label></th>
			<td>http://<input id="website_url" type="text" name="website_url" class="validation"/></td>
		</tr>
	</table>
</form>
