<link href="/css/television/index.css" rel="stylesheet" type="text/css" />
<!-- ------------------------------------------------------------------------------------------------------------------------------------------------------ -->
<div class="recommend_today">
	<div class="action_bar_background"></div>
	<div id="action_bar">
		<a id="action_prev" onmouseover="$(this).addClass('hover')" onmouseout="$(this).removeClass('hover')"></a>
		<div class="action_content">
			<ul>
{foreach key=key item=item from=$recommend_movie}
				<li {if $key==8}class="zoom"{/if} data_id="{$item.movie_id}"><img data="http://{$item.movie_list_img_url}" alt="{$item.movie_name}" onerror="this.src='/images/nopic.gif'"/></li>
{/foreach}
			</ul>
		</div>
		<a id="action_next" onmouseover="$(this).addClass('hover')" onmouseout="$(this).removeClass('hover')"></a>
	</div>
	<div class="recommend_movie_detail" id="recommend_movie_detail">
{foreach key=key item=item from=$recommend_movie}
		<div class="detail{if $key==8} action{/if}" data_id="{$item.movie_id }">
			<div class="left">
				<a href="/movie_detail_id_{$item.movie_id}.html" title="{$item.movie_name}">
					<img data="http://{$item.movie_list_img_url}" alt="{$item.movie_name }" onerror="this.src='/images/nopic.gif'"/>
				</a>
			</div>
			<div class="right">
				<h1><a href="/movie_detail_id_{$item.movie_id}.html" title="{$item.movie_name}">{$item.movie_name}</a></h1>
				{if $item.movie_starring}<p class="starring"><strong> 主演：{$item.movie_starring}</strong></p>{/if}
				{if $item.movie_director}<p class="director"><strong> 导演：{$item.movie_director}</strong></p>{/if}
				{if $item.movie_release_date}<p class="release_date"><strong> 上映日期：{$item.movie_release_date}</strong></p>{/if}
				{if $item.movie_hot}<p class="hot"><strong> 浏览次数：{$item.movie_hot}</strong></p>{/if}
				{if $item.movie_description}<p class="description">{$item.movie_description}</p>{/if}
			</div>
		</div>
{/foreach}
	</div>
</div>
<div class="search_box">
	<form name="formsearch" method="get" action="/television/Search">
		<div class="logo"><img src="/images/Logo.png" alt="由我影视导航"/></div>
		<div class="top20 keyword"><input type="text" name="searchword" value="" class="search_word" id="search_word"/></div>
		<div class="top20 left5 width97"><input type="submit" value="由我搜索" class="search_submit"/></div>
		<div class="top15 left5 share">
			<span class="bdshare_t bds_tools_32 get-codes-bdshare">
			    <div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">
			        <span class="bds_more">分享</span>
			    </div>
			</span>
		</div>
	</form>
	<link href="/js/jquery/autocomplete/styles.css" rel="stylesheet" type="text/css" />
	<script src="/js/jquery/autocomplete/jquery.autocomplete-min.js"></script>
</div>
<div class="recommend_website">
	<h3>推荐网站</h3>
	<ul>
	<!--{foreach key=key item=item from=$recommend_website}-->
		<li><a target="_blank" href="/television/website/hit?id={$item.website_id}&url={$item.website_url}" title="由我影视导航">{$item.website_name}</a></li>
	<!--{/foreach}-->
	</ul>
</div>

<div class="hot_movie">
	<h3>热门影视</h3>
	<ul>
	<!--{foreach key=key item=item from=$hot_movie}-->
		<li><a href="/movie_detail_id_{$item.movie_id}.html" title="{$item.movie_name}">{$item.movie_name}</a></li>
	<!--{/foreach}-->
	</ul>
</div>
<!-- ------------------------------------------------------------------------------------------------------------------------------------------------------ -->
<script src="/js/television/index.js"></script>