<ul>
	<li id="shop"><a href="/intranet_television" title="상점관리">影视娱乐</a></li>
	<li>|</li>
	<li class="active float_right">
		<a href="/intranet/crawl/clear-error-log" target="_blank">清除采集错误日志</a> |
		<a href="/intranet/crawl/download-error-log" target="_blank">下载采集错误日志</a> |
		<a href="/intranet/crawl/auto" target="_blank">自动采集</a> |
		<a href="/intranet/sql/backup">数据备份</a> |
		<a href="/intranet/sql/import" target="_blank">数据导入</a> |
		<a href="/intranet/sitemap" target="_blank">重置sitemap</a> |
		<a class="logout" title="로그아웃">注销</a>
	</li>
</ul>