<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<script src="<?php echo $this->layout()->domain->base;?>js/jquery/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->domain->base;?>/js/intranet/default.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->layout()->domain->base;?>/css/intranet/default.css" media="all" />
</head>
<body>
<table style="border-collapse:collapse;border:none;width:100%;">
	<thead>
		<tr>
			<td id="header">
				<ul style="float:left;padding:10px;">
					<li uid="shop"><a href="<?php echo $this->layout()->domain->base;?>intranet_television" title="상점관리">影视娱乐</a></li>
					<li>|</li>
				</ul>
				<ul style="float:right;padding:10px;">
					<li class="active"><a class="logout" title="로그아웃">注销</a></li>
				</ul>
			</td>
		</tr>
	</thead>