<!DOCTYPE html>
<html>
<head>
	<meta name="baidu-site-verification" content="C9QKZT69wSVKSrnH" />
	<meta name="chinaz-site-verification" content="8b77bc1c-97ea-44d5-bc83-e3a2c68fa312" />
	<meta name="google-site-verification" content="CCbVahem7Ve83OKF1aWYXSYAXzBCvQ1ifNX55tiUlJ0" />
	<meta name="robots" content="index,follow">
	<meta name="googlebot" content="index,follow">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{$title}</title>
	<meta name="keywords" content="{$keywords}" />
	<meta name="description" content="{$description}" />
	<link rel="shortcut icon" href="/favicon.ico" />
	<link href="/css/television/default.css" rel="stylesheet" type="text/css" />
	<script src="/js/jquery/jquery.js"></script>
	<script src="/js/television/default.js"></script>
</head>
<body>
	<div class="header">
	    <div id="bdshare" class="bdshare_t bds_tools get-codes-bdshare">
	        <span class="bds_more">分享到：</span>
	        <a class="bds_qzone"></a>
	        <a class="bds_tsina"></a>
	        <a class="bds_tqq"></a>
	        <a class="bds_renren"></a>
			<a class="shareCount"></a>
	    </div>
	</div>
	<div class="content">
		<div class="center">
		{include file=$content}
		</div>
		<div style="clear:both;"></div>
	</div>
	<div class="footer">
	{include file=$footer}
	</div>
</body>
</html>