<link href="/css/intranet/television/category/index.css" rel="stylesheet" type="text/css" />
<div class="location"><span>影视娱乐管理->分类管理</span></div>
<div id="content">
	<div id="action_bar">
		<button id="reset">RENAME</button>
		<button id="add">+</button>
		<button id="del">-</button>
	</div>
	<select name="category_code" class="category" multiple="multiple" size="20">
	<?php foreach($this->lists AS $key=>$value):?>
		<option value="<?php echo $value['category_id']?>||<?php echo $value['category_code']?>"><?php echo $value['category_name']?></option>
	<?php endforeach;?>
	</select>
	<select name="category_code_2" class="category" multiple="multiple" size="20">
	</select>
	<select name="category_code_3" class="category" multiple="multiple" size="20">
	</select>
	<select name="category_code_4" class="category" multiple="multiple" size="20">
	</select>
	<select name="category_code_5" class="category" multiple="multiple" size="20">
	</select>
	<select name="category_code_6" class="category" multiple="multiple" size="20">
	</select>
</div>
<script src="/js/intranet/television/category/index.js" type="text/javascript"></script>
