<!-- --------------------------------------------------------------------------------------------- -->
<script type="text/javascript" src="/js/jquery/jquery.js"></script>
<link href="/css/intranet/television/searchWord/startCrawl.css" rel="stylesheet" type="text/css" />
<!-- --------------------------------------------------------------------------------------------- -->

<script>
	var SEARCH_WORD_VALUE	= <?php echo json_encode($this->search_word_value);?>;
	var CRAWL_FILES			= <?php echo json_encode($this->crawl_files);?>;
</script>
<h1>抓取关键字: <strong ><?php echo implode('</strong>,<strong> ',$this->search_word_value);?></strong></h1>
<button id="display">只显示失败</button>
<div id="crawl_failed">

</div>
<div id="crawl_content">

</div>
<script src="/js/intranet/television/searchWord/startCrawl.js" type="text/javascript"></script>