<div class="menu">
	<h3 class="title" title="影视娱乐基本管理">影视娱乐基本管理</h3>
	<ul>
		<li id="category"><a href="/intranet_television/category" title="影视娱乐">分类管理</a></li>
		<li id="website"><a href="/intranet_television/website" title="电影网址">网站管理</a></li>
		<li id="movie"><a href="/intranet_television/movie" title="电影影片 ">影片管理</a></li>
		<li id="search_word"><a href="/intranet_television/search-word" title="搜索关键字 ">搜索关键字</a></li>
	</ul>
</div>
<a id="open_menu">확대</a>